C4R-782 Practice Programs Search
code4romania/practice-for-good pull request #5
Opened 2022-10-21 14:43 UTC by dragos1195

Disclaimer: Search is bugged, works on a second button push. WIP

https://wearetribus.atlassian.net/browse/C4R-782

2022-10-24 09:50 UTC, birloiflorian requested changes

2022-10-24 09:50 UTC, birloiflorian commented on src/common/components/filter-modal/FilterModal.tsx
> +                            defaultValue={value ? value : undefined}
Aici daca nu are value, nu vine ca undefined oricum?

2022-10-24 09:50 UTC, birloiflorian commented on src/common/components/filter-modal/FilterModal.tsx
> +                        Aplica filtre
Internationalizare

2022-10-24 09:50 UTC, birloiflorian commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +      <p className='font-titilliumBold sm:text-4xl text-xl  text-black'>Programe de practică la ONG-uri din România</p>
Internationalizare

2022-10-24 09:50 UTC, birloiflorian commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +              Filtre
Internationalizare

2022-10-24 09:50 UTC, birloiflorian commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +              5
Aici nu ar trebui sa fie calculat?

2022-10-24 09:50 UTC, birloiflorian commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +            Cauta
Internationalizare

2022-10-25 11:34 UTC, dragos1195 commented on src/common/components/filter-modal/FilterModal.tsx
> +                            defaultValue={value ? value : undefined}
Removed

2022-10-25 11:34 UTC, dragos1195 commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +      <p className='font-titilliumBold sm:text-4xl text-xl  text-black'>Programe de practică la ONG-uri din România</p>
Added.

2022-10-25 11:34 UTC, dragos1195 commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +              5
Fixed.

2022-10-25 11:34 UTC, dragos1195 commented on src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
> +            Cauta
Added.

2022-10-25 13:37 UTC, birloiflorian approved these changes

2022-10-26 07:50 UTC, merged